In [3]:
#import Libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
# import dataset

#df=pd.read_excel('C:\Users\psuni\Desktop\Social audit dataset for python.csv')
df=pd.read_csv(r'C:\Users\psuni\Desktop\Social audit dataset for python.csv')
print(df.shape)
df.head()

(2000, 20)

,State,District,GramPanchayat,AuditDate,FinancialYear,SchemeName,WorkType,AuditedBy,TotalExpenditure,MisappropriationAmount,RecoveryAmount,IssuesFound,IssueType,AuditStatus,BeneficiariesCovered,ManDaysGenerated,WagesPaid,MaterialCost,ComplaintsReceived,ActionTaken
0,Tamil Nadu,Chennai,GP_Chennai_34,18-11-2023,2021-22,PMGSY,School Building,SAU Team B,449857.43,109486.70,59286.30,1,Fund Diversion,Closed,63,4420,647742.72,521157.67,22,FIR Filed
1,Tamil Nadu,Chennai,GP_Chennai_40,27-06-2024,2023-24,NSAP,Pond Desilting,SAU Team B,923746.55,22216.64,20637.67,9,Wage Delay,Pending Recovery,365,2409,98301.41,23757.77,22,Warning Issued
2,Maharashtra,Mumbai,GP_Mumbai_76,30-05-2024,2021-22,NSAP,Toilet Construction,SAU Team A,286856.30,31249.04,71307.49,5,Incomplete Work,Completed,287,3742,99570.70,246425.59,21,No Action
3,Andhra Pradesh,Vizag,GP_Vizag_48,14-03-2024,2021-22,SBM-G,Road Construction,District Audit Unit,1709666.11,98793.38,78197.94,9,Fund Diversion,ATR Pending,392,7176,748214.61,520650.51,7,NaN
4,Maharashtra,Mumbai,GP_Mumbai_50,20-07-2024,2023-24,NSAP,Pond Desilting,SAU Team B,642423.90,137493.94,25496.21,4,Wage Delay,Pending Recovery,289,4085,889828.45,NaN,10,No Action

In [17]:
## Basic Explorations

print(f"Shape:{df.shape}")
print(f"Total cells:{df.size}")

print("\n")
## First and last 5 rows

print("============================================")
print(f"-----HEAD(first 5 rows)-------------")
print("============================================")
print(df.head())

print("\n")
print("============================================")
print(f"-----TAIL(Last 5 rows)-------------")
print("============================================")
print(df.tail())

Shape:(2000, 20)
Total cells:40000


============================================
-----HEAD(first 5 rows)-------------
============================================
            State District  GramPanchayat   AuditDate FinancialYear  \
0      Tamil Nadu  Chennai  GP_Chennai_34  18-11-2023       2021-22
1      Tamil Nadu  Chennai  GP_Chennai_40  27-06-2024       2023-24
2     Maharashtra   Mumbai   GP_Mumbai_76  30-05-2024       2021-22
3  Andhra Pradesh    Vizag    GP_Vizag_48  14-03-2024       2021-22
4     Maharashtra   Mumbai   GP_Mumbai_50  20-07-2024       2023-24

  SchemeName             WorkType            AuditedBy  TotalExpenditure  \
0      PMGSY      School Building           SAU Team B         449857.43
1       NSAP       Pond Desilting           SAU Team B         923746.55
2       NSAP  Toilet Construction           SAU Team A         286856.30
3      SBM-G    Road Construction  District Audit Unit        1709666.11
4       NSAP       Pond Desilting           SAU Team B         642423.90

   MisappropriationAmount  RecoveryAmount  IssuesFound        IssueType  \
0               109486.70        59286.30            1   Fund Diversion
1                22216.64        20637.67            9       Wage Delay
2                31249.04        71307.49            5  Incomplete Work
3                98793.38        78197.94            9   Fund Diversion
4               137493.94        25496.21            4       Wage Delay

        AuditStatus  BeneficiariesCovered  ManDaysGenerated  WagesPaid  \
0            Closed                    63              4420  647742.72
1  Pending Recovery                   365              2409   98301.41
2         Completed                   287              3742   99570.70
3       ATR Pending                   392              7176  748214.61
4  Pending Recovery                   289              4085  889828.45

   MaterialCost  ComplaintsReceived     ActionTaken
0     521157.67                  22       FIR Filed
1      23757.77                  22  Warning Issued
2     246425.59                  21       No Action
3     520650.51                   7             NaN
4           NaN                  10       No Action


============================================
-----TAIL(Last 5 rows)-------------
============================================
              State   District    GramPanchayat   AuditDate FinancialYear  \
1995      Karnataka     Mysore     GP_Mysore_61  17-05-2022       2022-23
1996         Kerala  Ernakulam  GP_Ernakulam_98  15-10-2022       2021-22
1997  Uttar Pradesh    Lucknow    GP_Lucknow_18  20-03-2022       2023-24
1998      Karnataka  Bangalore  GP_Bangalore_48  12-02-2024       2021-22
1999      Rajasthan     Jaipur     GP_Jaipur_72  21-07-2024       2023-24

     SchemeName           WorkType            AuditedBy  TotalExpenditure  \
1995      SBM-G     Pond Desilting           SAU Team A         648650.36
1996     PMAY-G         Water Tank  District Audit Unit        1663399.18
1997       NSAP    School Building           SAU Team B        1518856.10
1998     PMAY-G  Road Construction           SAU Team A        1932024.37
1999    MGNREGA         Water Tank           SAU Team A         367175.01

      MisappropriationAmount  RecoveryAmount  IssuesFound  \
1995               148537.48        36414.67            9
1996                 5340.78        12118.62            6
1997                21428.76        56562.71            4
1998                60649.51             NaN            3
1999               108884.05        10614.56            5

                 IssueType   AuditStatus  BeneficiariesCovered  \
1995        No Muster Roll   ATR Pending                   465
1996        Fund Diversion  Under Review                   402
1997  Material Overbilling     Completed                   261
1998        No Muster Roll   ATR Pending                   307
1999     Ghost Beneficiary     Completed                   493

      ManDaysGenerated  WagesPaid  MaterialCost  ComplaintsReceived  \
1995              6163  240481.79      62000.18                   6
1996               721  942116.77     183853.49                   5
1997              7396  968077.90     503069.15                  19
1998              1558  312740.88     615499.64                   0
1999              4089  988293.37     496429.73                  12

             ActionTaken
1995  Recovery Initiated
1996           FIR Filed
1997           No Action
1998  Recovery Initiated
1999  Suspended Official

In [25]:
## Datatypes
print("\n")
print("======================================================")
print("----------------------INFO----------------------------")
print("======================================================")
df.info()


print("\n")
print("==========================================================")
print("------------------------DESCRIPTION-----------------------")
print("==========================================================")
df.describe()

======================================================
----------------------INFO----------------------------
======================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 20 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   State                   2000 non-null   object
 1   District                2000 non-null   object
 2   GramPanchayat           2000 non-null   object
 3   AuditDate               2000 non-null   object
 4   FinancialYear           2000 non-null   object
 5   SchemeName              2000 non-null   object
 6   WorkType                2000 non-null   object
 7   AuditedBy               2000 non-null   object
 8   TotalExpenditure        2000 non-null   float64
 9   MisappropriationAmount  1801 non-null   float64
 10  RecoveryAmount          1804 non-null   float64
 11  IssuesFound             2000 non-null   int64
 12  IssueType               1792 non-null   object
 13  AuditStatus             2000 non-null   object
 14  BeneficiariesCovered    2000 non-null   int64
 15  ManDaysGenerated        2000 non-null   int64
 16  WagesPaid               2000 non-null   float64
 17  MaterialCost            1805 non-null   float64
 18  ComplaintsReceived      2000 non-null   int64
 19  ActionTaken             1801 non-null   object
dtypes: float64(5), int64(4), object(11)
memory usage: 312.6+ KB


==========================================================
------------------------DESCRIPTION-----------------------
==========================================================

,TotalExpenditure,MisappropriationAmount,RecoveryAmount,IssuesFound,BeneficiariesCovered,ManDaysGenerated,WagesPaid,MaterialCost,ComplaintsReceived
count,2.000000e+03,1801.000000,1804.000000,2000.000000,2000.000000,2000.000000,2000.000000,1805.000000,2000.000000
mean,1.033106e+06,76446.711094,40077.605610,5.514500,252.821500,4058.730500,515555.986460,404413.396753,12.165500
std,5.600802e+05,43251.696237,22980.853537,3.491545,144.072465,2287.049609,281383.512293,225807.526839,7.179476
min,5.036113e+04,17.800000,19.250000,0.000000,10.000000,100.000000,20499.790000,10087.080000,0.000000
25%,5.664719e+05,38510.670000,20384.472500,3.000000,124.000000,2097.750000,268687.360000,212191.780000,6.000000
50%,1.030536e+06,78164.430000,39976.170000,5.000000,257.000000,4077.000000,513757.790000,404937.610000,12.000000
75%,1.508291e+06,113763.710000,59249.452500,9.000000,376.250000,6030.000000,758425.725000,590883.880000,18.000000
max,1.999289e+06,149972.510000,79991.410000,11.000000,499.000000,7998.000000,998816.990000,799428.460000,24.000000

In [54]:
### Unique Values
print("\n")
print("=====================================================================")
print("                       STATE LIST                         ")
print("=====================================================================")
print(df['State'].unique())
print(f"Total States:{df['State'].nunique()}")
#print("\n")

print("\n")
print("==========================================================")
print("                       SCHEME NAME LIST                   ")
print("==========================================================")
print(df['SchemeName'].unique())
print(f"Total Schemes:{df['SchemeName'].nunique()}")
print("\n")
print(df['SchemeName'].value_counts())
print("\n")

#print("\n")
print("==========================================================")
print("                       WORK TYPE LIST                   ")
print("==========================================================")
print(df['WorkType'].unique())
print(f"Total Worktypes:{df['WorkType'].nunique()}")
print("\n")
print(df['WorkType'].value_counts())
print("\n")

print("==========================================================")
print("                       ISSUE TYPE LIST                   ")
print("==========================================================")
print(df['IssueType'].unique())
print(f"Total issue types:{df['IssueType'].nunique()}")
print("\n")
print(df['IssueType'].value_counts())

print("\n")
print("==========================================================")
print("                       AUDIT STATUS                       ")
print("==========================================================")
print(df['AuditStatus'].value_counts())
print("\n")

print("==========================================================")
print("                       AUDITED BY                        ")
print("==========================================================")
print(df['AuditedBy'].value_counts())
print("\n")

print("==========================================================")
print("                      FINANCIAL YEAR                      ")
print("==========================================================")
print(df['FinancialYear'].value_counts())
print("\n")

=====================================================================
                       STATE LIST
=====================================================================
['Tamil Nadu' 'Maharashtra' 'Andhra Pradesh' 'Rajasthan' 'Karnataka'
 'Uttar Pradesh' 'Bihar' 'Kerala']
Total States:8


==========================================================
                       SCHEME NAME LIST
==========================================================
['PMGSY' 'NSAP' 'SBM-G' 'PMAY-G' 'MGNREGA']
Total Schemes:5


SchemeName
PMAY-G     439
MGNREGA    398
NSAP       392
SBM-G      386
PMGSY      385
Name: count, dtype: int64


==========================================================
                       WORK TYPE LIST
==========================================================
['School Building' 'Pond Desilting' 'Toilet Construction'
 'Road Construction' 'Water Tank']
Total Worktypes:5


WorkType
Road Construction      420
Pond Desilting         411
School Building        406
Water Tank             390
Toilet Construction    373
Name: count, dtype: int64


==========================================================
                       ISSUE TYPE LIST
==========================================================
['Fund Diversion' 'Wage Delay' 'Incomplete Work' 'Ghost Beneficiary'
 'Material Overbilling' nan 'No Muster Roll']
Total issue types:6


IssueType
Wage Delay              311
Incomplete Work         308
No Muster Roll          300
Fund Diversion          296
Ghost Beneficiary       292
Material Overbilling    285
Name: count, dtype: int64


==========================================================
                       AUDIT STATUS
==========================================================
AuditStatus
Under Review        426
Closed              418
ATR Pending         414
Pending Recovery    378
Completed           364
Name: count, dtype: int64


==========================================================
                       AUDITED BY
==========================================================
AuditedBy
SAU Team A             680
SAU Team B             667
District Audit Unit    653
Name: count, dtype: int64


==========================================================
                      FINANCIAL YEAR
==========================================================
FinancialYear
2022-23    519
2021-22    511
2023-24    489
2024-25    481
Name: count, dtype: int64

In [59]:
# ============ Correction of  NaN ============

#  having columns with Numbers   fill with 0 
df['MisappropriationAmount'] = df['MisappropriationAmount'].fillna(0)
df['RecoveryAmount'] = df['RecoveryAmount'].fillna(0)
df['MaterialCost'] = df['MaterialCost'].fillna(0)

#   having columns with Text   fill with  Default text
df['IssueType'] = df['IssueType'].fillna('Not Reported')
df['ActionTaken'] = df['ActionTaken'].fillna('No Action Taken')

# ============ Correction of Datatype ============

# convert 'AuditDate' datatype  object to Date type 
df['AuditDate'] = pd.to_datetime(df['AuditDate'], dayfirst=True, errors='coerce')

print("\n")
print("==========================================================")
print("                       AFTER CORRECTION                   ")
print("==========================================================")
df.info()
print("\nNulls:", df.isnull().sum().sum())

KeyError: 'MisappropriationAmount'

In [61]:
# ============ COLUMN RENAME - CLEANING ============

# PROPER
df.rename(columns={
    'State': 'State',
    'District': 'District',
    'GramPanchayat': 'Gram_Panchayat',
    'AuditDate': 'Audit_Date',
    'FinancialYear': 'Financial_Year',
    'SchemeName': 'Scheme_Name',
    'WorkType': 'Work_Type',
    'AuditedBy': 'Audited_By',
    'TotalExpenditure': 'Total_Expenditure',
    'MisappropriationAmount': 'Misappropriation_Amount',
    'RecoveryAmount': 'Recovery_Amount',
    'IssuesFound': 'Issues_Found',
    'IssueType': 'Issue_Type',
    'AuditStatus': 'Audit_Status',
    'BeneficiariesCovered': 'Beneficiaries_Covered',
    'ManDaysGenerated': 'Man_Days_Generated',
    'WagesPaid': 'Wages_Paid',
    'MaterialCost': 'Material_Cost',
    'ComplaintsReceived': 'Complaints_Received',
    'ActionTaken': 'Action_Taken'
}, inplace=True)

# After cleaning
print("\n")
print("==========================================================")
print("                       AFTER CORRECTION                   ")
print("==========================================================")
print(df.columns.tolist())
print("\n")
df.head(2)

==========================================================
                       AFTER CORRECTION
==========================================================
['State', 'District', 'Gram_Panchayat', 'Audit_Date', 'Financial_Year', 'Scheme_Name', 'Work_Type', 'Audited_By', 'Total_Expenditure', 'Misappropriation_Amount', 'Recovery_Amount', 'Issues_Found', 'Issue_Type', 'Audit_Status', 'Beneficiaries_Covered', 'Man_Days_Generated', 'Wages_Paid', 'Material_Cost', 'Complaints_Received', 'Action_Taken']

,State,District,Gram_Panchayat,Audit_Date,Financial_Year,Scheme_Name,Work_Type,Audited_By,Total_Expenditure,Misappropriation_Amount,Recovery_Amount,Issues_Found,Issue_Type,Audit_Status,Beneficiaries_Covered,Man_Days_Generated,Wages_Paid,Material_Cost,Complaints_Received,Action_Taken
0,Tamil Nadu,Chennai,GP_Chennai_34,2023-11-18,2021-22,PMGSY,School Building,SAU Team B,449857.43,109486.70,59286.30,1,Fund Diversion,Closed,63,4420,647742.72,521157.67,22,FIR Filed
1,Tamil Nadu,Chennai,GP_Chennai_40,2024-06-27,2023-24,NSAP,Pond Desilting,SAU Team B,923746.55,22216.64,20637.67,9,Wage Delay,Pending Recovery,365,2409,98301.41,23757.77,22,Warning Issued

In [63]:
print("\n")
print("======================================================")
print("----------------------INFO----------------------------")
print("======================================================")
df.info()


print("\n")
print("==========================================================")
print("------------------------DESCRIPTION-----------------------")
print("==========================================================")
df.describe()

======================================================
----------------------INFO----------------------------
======================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   State                    2000 non-null   object
 1   District                 2000 non-null   object
 2   Gram_Panchayat           2000 non-null   object
 3   Audit_Date               2000 non-null   datetime64[ns]
 4   Financial_Year           2000 non-null   object
 5   Scheme_Name              2000 non-null   object
 6   Work_Type                2000 non-null   object
 7   Audited_By               2000 non-null   object
 8   Total_Expenditure        2000 non-null   float64
 9   Misappropriation_Amount  2000 non-null   float64
 10  Recovery_Amount          2000 non-null   float64
 11  Issues_Found             2000 non-null   int64
 12  Issue_Type               2000 non-null   object
 13  Audit_Status             2000 non-null   object
 14  Beneficiaries_Covered    2000 non-null   int64
 15  Man_Days_Generated       2000 non-null   int64
 16  Wages_Paid               2000 non-null   float64
 17  Material_Cost            2000 non-null   float64
 18  Complaints_Received      2000 non-null   int64
 19  Action_Taken             2000 non-null   object
dtypes: datetime64[ns](1), float64(5), int64(4), object(10)
memory usage: 312.6+ KB


==========================================================
------------------------DESCRIPTION-----------------------
==========================================================

,Audit_Date,Total_Expenditure,Misappropriation_Amount,Recovery_Amount,Issues_Found,Beneficiaries_Covered,Man_Days_Generated,Wages_Paid,Material_Cost,Complaints_Received
count,2000,2.000000e+03,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000
mean,2023-05-29 00:40:19.200000,1.033106e+06,68840.263340,36150.000260,5.514500,252.821500,4058.730500,515555.986460,364983.090570,12.165500
min,2022-01-01 00:00:00,5.036113e+04,0.000000,0.000000,0.000000,10.000000,100.000000,20499.790000,0.000000,0.000000
25%,2022-09-17 00:00:00,5.664719e+05,26527.172500,14011.082500,3.000000,124.000000,2097.750000,268687.360000,146932.847500,6.000000
50%,2023-05-26 00:00:00,1.030536e+06,68031.715000,35480.705000,5.000000,257.000000,4077.000000,513757.790000,360964.000000,12.000000
75%,2024-02-15 06:00:00,1.508291e+06,109508.007500,56923.072500,9.000000,376.250000,6030.000000,758425.725000,572844.527500,18.000000
max,2024-09-26 00:00:00,1.999289e+06,149972.510000,79991.410000,11.000000,499.000000,7998.000000,998816.990000,799428.460000,24.000000
std,NaN,5.600802e+05,46993.322475,24867.488337,3.491545,144.072465,2287.049609,281383.512293,245792.016161,7.179476

In [74]:
# ============HANDLING DUPLICATE VALUES  ============

print(f"Total rows: {len(df)}")
print(f"Duplicate rows: {df.duplicated().sum()}")

# REMOVING DUPLICATES
df.drop_duplicates(inplace=True)

print(f"After removing duplicates: {len(df)} rows")


print("\n")
print("==========================================================")
print(f"                   CLEANED DATASET                        ")
print("==========================================================")


df.info()

Total rows: 1916
Duplicate rows: 0
After removing duplicates: 1916 rows


==========================================================
                   CLEANED DATASET
==========================================================
<class 'pandas.core.frame.DataFrame'>
Index: 1916 entries, 0 to 1999
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   State                    1916 non-null   object
 1   District                 1916 non-null   object
 2   Gram_Panchayat           1916 non-null   object
 3   Audit_Date               1916 non-null   datetime64[ns]
 4   Financial_Year           1916 non-null   object
 5   Scheme_Name              1916 non-null   object
 6   Work_Type                1916 non-null   object
 7   Audited_By               1916 non-null   object
 8   Total_Expenditure        1916 non-null   float64
 9   Misappropriation_Amount  1916 non-null   float64
 10  Recovery_Amount          1916 non-null   float64
 11  Issues_Found             1916 non-null   int64
 12  Issue_Type               1916 non-null   object
 13  Audit_Status             1916 non-null   object
 14  Beneficiaries_Covered    1916 non-null   int64
 15  Man_Days_Generated       1916 non-null   int64
 16  Wages_Paid               1916 non-null   float64
 17  Material_Cost            1916 non-null   float64
 18  Complaints_Received      1916 non-null   int64
 19  Action_Taken             1916 non-null   object
dtypes: datetime64[ns](1), float64(5), int64(4), object(10)
memory usage: 314.3+ KB

In [76]:
# REMOVING UNWANTED COLUMNS#

# Audit_Date column is reduntant data and we can do our insights using financial year,so dropping audit_Date #

df.drop(columns=['Audit_Date'],inplace=True)

print("\n")

KeyError: "['Audit_Date'] not found in axis"

In [79]:

print("==========================================================")
print(f"                   CLEANED DATASET                        ")
print("==========================================================")
df.info()

==========================================================
                   CLEANED DATASET
==========================================================
<class 'pandas.core.frame.DataFrame'>
Index: 1916 entries, 0 to 1999
Data columns (total 19 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   State                    1916 non-null   object
 1   District                 1916 non-null   object
 2   Gram_Panchayat           1916 non-null   object
 3   Financial_Year           1916 non-null   object
 4   Scheme_Name              1916 non-null   object
 5   Work_Type                1916 non-null   object
 6   Audited_By               1916 non-null   object
 7   Total_Expenditure        1916 non-null   float64
 8   Misappropriation_Amount  1916 non-null   float64
 9   Recovery_Amount          1916 non-null   float64
 10  Issues_Found             1916 non-null   int64
 11  Issue_Type               1916 non-null   object
 12  Audit_Status             1916 non-null   object
 13  Beneficiaries_Covered    1916 non-null   int64
 14  Man_Days_Generated       1916 non-null   int64
 15  Wages_Paid               1916 non-null   float64
 16  Material_Cost            1916 non-null   float64
 17  Complaints_Received      1916 non-null   int64
 18  Action_Taken             1916 non-null   object
dtypes: float64(5), int64(4), object(10)
memory usage: 299.4+ KB

In [80]:
# ADDING CALCULATED COLUMN 

#Pending_Recovery_amt=missappropriation_amt-  Recovery amount

df['Pending_Recovery'] = df['Misappropriation_Amount'] - df['Recovery_Amount']

df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1916 entries, 0 to 1999
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   State                    1916 non-null   object
 1   District                 1916 non-null   object
 2   Gram_Panchayat           1916 non-null   object
 3   Financial_Year           1916 non-null   object
 4   Scheme_Name              1916 non-null   object
 5   Work_Type                1916 non-null   object
 6   Audited_By               1916 non-null   object
 7   Total_Expenditure        1916 non-null   float64
 8   Misappropriation_Amount  1916 non-null   float64
 9   Recovery_Amount          1916 non-null   float64
 10  Issues_Found             1916 non-null   int64
 11  Issue_Type               1916 non-null   object
 12  Audit_Status             1916 non-null   object
 13  Beneficiaries_Covered    1916 non-null   int64
 14  Man_Days_Generated       1916 non-null   int64
 15  Wages_Paid               1916 non-null   float64
 16  Material_Cost            1916 non-null   float64
 17  Complaints_Received      1916 non-null   int64
 18  Action_Taken             1916 non-null   object
 19  Pending_Recovery         1916 non-null   float64
dtypes: float64(6), int64(4), object(10)
memory usage: 314.3+ KB

In [ ]:
# Checked for inconsistencies using unique() above, found that all valuesin the dataset are standardized